[package]
name = "rust_Example"
version = "0.1.0"
edition = "2021"
authors = ["Andrew <a@example.com>", "Mel <m@example.com>"]
 
[dependencies]
tokio = { version = "1.15.0", features = ["full"] }
tera = "1.15.0"
rocket = "0.5.0-rc.1"
rocket_codegen = "0.4.4"
rocket_dyn_templates = {version = "0.1.0-rc.1", features=["tera"]}
 
[profile.release] # Some compiler options for release.
lto = true
opt-level = 0